travis:
  secure:
    BINSTAR_TOKEN: liKawTQSxmG1Ff7KjcoU8lqezbBtq2NgzPv1hJbYC/i7sdA88qD7vXUjzOcQ6aKpLvEN0BAeLcUEyMfxyy/kaFsNNy2TjJBz7ggRw68FMZ614zNp7xY6ZS95aaYZRHs95e7wfaajYFhyK5zklgPN66Jyz85qOzcOfxwFHFJCRbBNUS0OGe7os/rqqDGcKWhkHWxib/jm122A905dfJtRY/V0U9zMbRw9mHrA30ZHu2Yaqok+Xk9lryjW4dYiwjSpEDA+rt6AkNwwhJyPhiJYacIxlb1pQ+sWDEyIQAivMIXTKw+RSu9oeKM52jmNIDtTrGP0Z0W8gJHg4VpGgYIgnzFfyhGKWw8/YxUAW+NCDZiAGHU+gl3liXoz8XbeI3J7dqaFkgyamYzn5h0BGnZrJdSrTn1LouEhGS3criCVVN0jTr3fYB7T4ksv+cRsVwo1yZimKaifdvEKgMGxipfjiWU3lfboyIPd/n8BTpmgOl0VrlrkHFDNLFzltuGsAMn63DBolhVdkj4QVGH69V8cHGWPMYkFGgjMRneJaMzZndDNNBLEcVPJkvWqBZDp1dD5QGwRW6sx2I0rgCA2oI3rlEmwPzI9vu9+BbV1HUGOJOuUX1H7ChzAkAJ/FbCMx5la/5a9brosuD1/kbd4QacC4bQzbSlGcGXwW9QqjA9m9S0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
