travis:
  secure:
    BINSTAR_TOKEN: PVuJjzHDYCyY6cHRxn3VmmFA/2ud5Nys9cPJn1Wi4ZLO9F3CfCOz+KptmUT5U82K8dH1oCyMAnhdN8SZxu+tczx+CXa8gGDC/5rqAQIAz4skCZ1EVCnQqbdKRVBDomJ3jMdi84edNMYc2iinbQchDh1QNOhF+YpA0zKXdQ2jwfyxkFynCDE2eJqDZd/TjsalUkcuU8rbBu+67UX7/uYEvj2NzKZ19qs7OMYtoCNSNX0PsJf6hn1mVnSaG6gzGUvG7aobuki6JUhV5yBKRdunsMPo2K5iVSdHXvmsHpecARzEUQm9CjPCFBy6h2cqpE4MauydMmhs2sfFPUaPfEq8sNSAdaqgt/XjA7mNJQzEplBVJMi4X3a9c/sZlKptJ9mjOvIzi9qtQBWG78EsAiAahkrjb+YxWECQPVgAj2m5jCv30jfQTSRs2HhAQ5Fq1PJ7URoYYDVGdI/POIPMTSosUUNTWsb6ZH1nVpZqmFo/a8AAjx7APQFg8Dbb6O390I9aaM4dKQ0XDAvnl1SusVMTm+PTwvzE2srG18CHFhONsN/b0uIOBOxUhN//wI0AU8FO3FuSSbDBlKHM7l9g76wcDwtxKdoav54ulQCsVkoBWnFwtnh/kwcg6J9zkPKEiHNFZ3EnP7vqTCA7hEXjq6RoxaKY8Haqtd7rDsModarUjbI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
